# Generated by Django 5.0.1 on 2026-04-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMedication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_raw", models.CharField(max_length=255)),
                ("name_display", models.CharField(blank=True, max_length=255, null=True)),
                ("rxcui", models.CharField(blank=True, max_length=32, null=True)),
                ("dosage", models.CharField(blank=True, max_length=255, null=True)),
                ("frequency", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.CharField(blank=True, max_length=255, null=True)),
                ("route", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("ambiguous", "Ambiguous"),
                            ("unverified", "Unverified"),
                            ("failed", "Failed"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                ("verification_detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_medications",
                        to="documents.medicaldocument",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at", "-created_at", "id"]},
        ),
    ]
