# Generated by Django 5.0.1 on 2026-04-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_patientmedication'),
        ('psychology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringlog',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientmedication',
            name='source_document',
        ),
        migrations.CreateModel(
            name='ClinicalCaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=16)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('closed', 'Closed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_case_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrisisEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed')], default='open', max_length=16)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('emotion_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='psychology.emotionassessment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_escalations', to=settings.AUTH_USER_MODEL)),
                ('physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crisis_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('cataract', 'Cataract'), ('retinopathy', 'Retinopathy'), ('foot_ulcer', 'Foot Ulcer'), ('infrared', 'Infrared')], max_length=32)),
                ('severity_grade', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CarePlan',
        ),
        migrations.DeleteModel(
            name='MonitoringLog',
        ),
        migrations.DeleteModel(
            name='PatientMedication',
        ),
    ]
