# Generated by Django 5.0.1 on 2026-04-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('barcode', 'Barcode'), ('voice', 'Voice'), ('photo', 'Photo')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('carbs_g', models.FloatField(default=0.0)),
                ('calories_kcal', models.FloatField(default=0.0)),
                ('sugar_g', models.FloatField(default=0.0)),
                ('gi', models.FloatField(default=0.0)),
                ('gl', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_food', models.CharField(max_length=255)),
                ('suggested_food', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('expected_gi_delta', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_substitutions', to=settings.AUTH_USER_MODEL)),
                ('meal_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='nutrition.meallog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories_kcal', models.FloatField()),
                ('target_carbs_g', models.FloatField()),
                ('target_protein_g', models.FloatField(default=0.0)),
                ('target_fat_g', models.FloatField(default=0.0)),
                ('target_sugar_g', models.FloatField(default=0.0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack_suggestion', models.CharField(blank=True, max_length=255)),
                ('hydration_ml', models.PositiveIntegerField(default=0)),
                ('glucose_recheck_minutes', models.PositiveIntegerField(default=30)),
                ('next_session_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_plan', to='nutrition.exercisesession')),
            ],
        ),
    ]
