# Generated by Django 6.0.4 on 2026-05-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meallog',
            name='patient',
        ),
        migrations.DeleteModel(
            name='FoodSubstitution',
        ),
        migrations.DeleteModel(
            name='MealLog',
        ),
    ]
