# Generated by Django 5.0.1 on 2026-05-03 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_remove_meallog_patient_delete_foodsubstitution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cuisine', models.CharField(choices=[('mediterranean', 'Mediterranean'), ('maghreb', 'Maghreb / North African'), ('middle_eastern', 'Middle Eastern'), ('western', 'Western')], default='mediterranean', max_length=30)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_snapshot', models.JSONField(default=dict)),
                ('week_summary', models.JSONField(default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('patient', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.JSONField(default=list)),
                ('preparation_time_minutes', models.PositiveSmallIntegerField(default=20)),
                ('calories_kcal', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('sugar_g', models.FloatField()),
                ('glycemic_index', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('glycemic_load', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('nutritional_source', models.CharField(choices=[('usda_validated', 'USDA Validated'), ('llm_estimated', 'LLM Estimated')], default='llm_estimated', max_length=20)),
                ('usda_breakdown', models.JSONField(default=list)),
                ('diabetes_rationale', models.TextField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.weeklymealplan')),
            ],
            options={
                'ordering': ['day_index', 'meal_type'],
                'unique_together': {('meal_plan', 'day_index', 'meal_type')},
            },
        ),
    ]
