services:
  caddy:
    image: caddy:2-alpine
    container_name: glunova-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - django_media:/media:ro
    depends_on:
      - django_app

  django_app:
    image: ghcr.io/edamhakim/glunova-django:latest
    container_name: glunova-django
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      AI_SERVICE_URL: http://fastapi_ai:8001
      FASTAPI_BASE_URL: http://fastapi_ai:8001
      DJANGO_DEBUG: "false"
    volumes:
      - django_media:/app/media
    depends_on:
      - fastapi_ai

  fastapi_ai:
    image: ghcr.io/edamhakim/glunova-fastapi:latest
    container_name: glunova-fastapi
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      FASTAPI_SKIP_STARTUP_WARMUP: "false"
    volumes:
      - ./models/screening:/app/screening/models
      - ./models/clinic:/app/clinic/models

volumes:
  caddy_data:
  caddy_config:
  django_media:
