# Generated by Django 6.0.4 on 2026-05-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='diabetes_type',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Prediabetes', 'Prediabetes')], default='Type 2', max_length=20),
        ),
    ]
