"""Repair DBs where 0001 was marked applied but CarePlan/CareTask/MedicationGuidance tables were never created."""

from django.db import migrations


def forwards(apps, schema_editor):
    with schema_editor.connection.cursor() as c:
        c.execute(
            "SELECT to_regclass('public.carecircle_careplan') IS NOT NULL"
        )
        if c.fetchone()[0]:
            return

    sql = """
CREATE TABLE "carecircle_careplan" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "notes" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "doctor_id" bigint NULL,
    "patient_id" bigint NOT NULL
);

ALTER TABLE "carecircle_careplan" ADD CONSTRAINT "carecircle_careplan_doctor_id_5a432636_fk_users_user_id"
    FOREIGN KEY ("doctor_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "carecircle_careplan" ADD CONSTRAINT "carecircle_careplan_patient_id_889433a2_fk_users_user_id"
    FOREIGN KEY ("patient_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "carecircle_careplan_doctor_id_5a432636" ON "carecircle_careplan" ("doctor_id");
CREATE INDEX "carecircle_careplan_patient_id_889433a2" ON "carecircle_careplan" ("patient_id");

CREATE TABLE "carecircle_caretask" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "status" varchar(16) NOT NULL,
    "due_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL,
    "assignee_id" bigint NULL,
    "care_plan_id" bigint NOT NULL
);

ALTER TABLE "carecircle_caretask" ADD CONSTRAINT "carecircle_caretask_assignee_id_9591d5e6_fk_users_user_id"
    FOREIGN KEY ("assignee_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "carecircle_caretask" ADD CONSTRAINT "carecircle_caretask_care_plan_id_d043ccdb_fk_carecircl"
    FOREIGN KEY ("care_plan_id") REFERENCES "carecircle_careplan" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "carecircle_caretask_assignee_id_9591d5e6" ON "carecircle_caretask" ("assignee_id");
CREATE INDEX "carecircle_caretask_care_plan_id_d043ccdb" ON "carecircle_caretask" ("care_plan_id");

CREATE TABLE "carecircle_medicationguidance" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "medication_name" varchar(255) NOT NULL,
    "guidance" text NOT NULL,
    "doctor_validated" boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "patient_id" bigint NOT NULL,
    "requested_by_id" bigint NULL
);

ALTER TABLE "carecircle_medicationguidance" ADD CONSTRAINT "carecircle_medicatio_patient_id_9526af87_fk_users_use"
    FOREIGN KEY ("patient_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "carecircle_medicationguidance" ADD CONSTRAINT "carecircle_medicatio_requested_by_id_333cd662_fk_users_use"
    FOREIGN KEY ("requested_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "carecircle_medicationguidance_patient_id_9526af87" ON "carecircle_medicationguidance" ("patient_id");
CREATE INDEX "carecircle_medicationguidance_requested_by_id_333cd662" ON "carecircle_medicationguidance" ("requested_by_id");
"""
    with schema_editor.connection.cursor() as c:
        c.execute(sql)


def backwards(apps, schema_editor):
    with schema_editor.connection.cursor() as c:
        c.execute('DROP TABLE IF EXISTS "carecircle_caretask" CASCADE;')
        c.execute('DROP TABLE IF EXISTS "carecircle_medicationguidance" CASCADE;')
        c.execute('DROP TABLE IF EXISTS "carecircle_careplan" CASCADE;')


class Migration(migrations.Migration):
    atomic = False  # DDL + multiple statements compatible with Postgres

    dependencies = [
        ("carecircle", "0002_familyupdate_source"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
