# Generated by Django 5.0.1 on 2026-05-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carecircle', '0003_create_missing_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretask',
            name='care_plan',
        ),
        migrations.RemoveField(
            model_name='caretask',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='medicationguidance',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicationguidance',
            name='requested_by',
        ),
        migrations.DeleteModel(
            name='CarePlan',
        ),
        migrations.DeleteModel(
            name='CareTask',
        ),
        migrations.DeleteModel(
            name='MedicationGuidance',
        ),
    ]
