# Generated by Django 5.2.11 on 2026-04-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0002_psychology_persistence_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='psychologyemotionlog',
            new_name='psychology__patient_4f645a_idx',
            old_name='psychology_p_patient_idx',
        ),
    ]
