# Generated by Django 6.0.4 on 2026-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0004_psychologyprofile_semantic_profile_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologyprofile',
            name='semantic_profile_json',
            field=models.JSONField(blank=True, default=dict, help_text='Sanadi-distilled cross-session semantic memory (stressors, triggers, trends, clinician review cues).'),
        ),
    ]
