# Generated by Django 5.0.1 on 2026-04-14 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=128)),
                ('storage_path', models.CharField(max_length=1024)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('extracted_json', models.JSONField(default=dict)),
                ('extracted_json_rules', models.JSONField(default=dict)),
                ('llm_provider_used', models.CharField(blank=True, max_length=64, null=True)),
                ('llm_refinement_status', models.CharField(choices=[('ok', 'Ok'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='skipped', max_length=16)),
                ('document_type_detected', models.CharField(blank=True, max_length=64, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientCaregiverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_document_links_as_caregiver', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_document_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='patientcaregiverlink',
            constraint=models.UniqueConstraint(fields=('patient', 'caregiver'), name='uniq_patient_caregiver_document_link'),
        ),
    ]
