# Generated by Django 5.0.1 on 2026-04-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(max_length=64)),
                ('context_id', models.CharField(max_length=64)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('technical_summary', models.TextField(blank=True)),
                ('plain_language_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('voice', 'Voice'), ('tongue', 'Tongue'), ('fusion', 'Voice + Tongue Fusion'), ('cataract', 'Cataract'), ('retinopathy', 'Retinopathy'), ('foot_ulcer', 'Foot Ulcer'), ('infrared', 'Infrared')], max_length=32)),
                ('score', models.FloatField()),
                ('risk_label', models.CharField(max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
            },
        ),
    ]
