# Generated by Django 6.0.4 on 2026-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_patientlabresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlabresult',
            name='is_out_of_range',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
