# Generated by Django 6.0.4 on 2026-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_patientlabresult_is_out_of_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedication',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
