# Generated by Django 5.0.1 on 2026-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_moderate_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthalert',
            name='agent_audience',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=16, null=True),
        ),
    ]
