const base = () => {
  const configured = process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, '')
  if (configured) return configured
  if (typeof window !== 'undefined') {
    return `${window.location.protocol}//${window.location.hostname}:8000`
  }
  return 'http://localhost:8000'
}

const apiPrefix = () => process.env.NEXT_PUBLIC_API_PREFIX || '/api/v1'

type Severity = 'info' | 'warning' | 'critical'

export type MonitoringAlert = {
  id: number
  patient_id: number
  patient_username: string
  severity: Severity
  title: string
  message: string
  status: 'active' | 'acknowledged' | 'resolved'
  triggered_at: string
  relative_time: string
  /** True when generated by the care agent for a specific viewer role */
  is_agent?: boolean
}

export type MonitoringTimelineItem = {
  type: 'screening' | 'progression' | 'alert' | 'log' | 'lab_result'
  timestamp: string
  relative_time: string
  patient_id: number
  patient_username: string
  title: string
  description: string
  value: string
}

export type MonitoringTierSummary = {
  tier: 'low' | 'high' | 'critical'
  count: number
  avg_score: number
  percentage: number
}

export type PatientLabResultRow = {
  id: number
  patient_id: string
  source_document_id: string
  source_document_filename: string
  source_document_created_at: string
  source_document_url: string | null
  source_document_preview_url: string | null
  source_document_mime_type: string | null
  test_name: string
  normalized_name: string
  value: string
  numeric_value: number | null
  unit: string | null
  reference_range: string | null
  is_out_of_range: boolean | null
  observed_at: string | null
  raw_payload: Record<string, unknown>
  created_at: string
  updated_at: string
}

async function getJson<T>(path: string) {
  const response = await fetch(`${base()}${apiPrefix()}${path}`, {
    headers: { 'Content-Type': 'application/json' },
    credentials: 'include',
  })
  if (!response.ok) throw new Error(await response.text())
  return response.json() as Promise<T>
}

export async function listMonitoringAlerts(patientId?: string) {
  const query = patientId ? `?patient_id=${encodeURIComponent(patientId)}` : ''
  return getJson<{ items: MonitoringAlert[]; total: number }>(`/monitoring/alerts${query}`)
}

export async function listMonitoringTimeline(patientId?: string, limit = 30) {
  const query = new URLSearchParams({ limit: String(limit) })
  if (patientId) query.set('patient_id', patientId)
  return getJson<{ items: MonitoringTimelineItem[]; total: number }>(`/monitoring/timeline?${query.toString()}`)
}

export async function getMonitoringProgression(patientId?: string) {
  const query = patientId ? `?patient_id=${encodeURIComponent(patientId)}` : ''
  return getJson<{ tiers: MonitoringTierSummary[]; total_patients: number }>(`/monitoring/progression${query}`)
}

export async function listLabResults(patientId: string) {
  const q = new URLSearchParams({ patient_id: patientId })
  return getJson<{ items: PatientLabResultRow[]; total: number }>(`/lab-results?${q.toString()}`)
}

export type RiskStratification = {
  current: {
    id: number
    patient_id: number
    patient_username: string
    tier: 'low' | 'high' | 'critical'
    score: number
    confidence: number
    recommendation: string
    reasons: string[]
    override_reason: string | null
    n_models_used: number
    assessed_at: string
    relative_time: string
  } | null
  previous: {
    tier: string
    score: number
    assessed_at: string
  } | null
  trend: 'first' | 'worsening' | 'improving' | 'stable'
  delta_score: number | null
}

export async function getRiskStratification(patientId?: string) {
  const query = patientId ? `?patient_id=${encodeURIComponent(patientId)}` : ''
  return getJson<RiskStratification>(`/monitoring/risk-stratification${query}`)
}

export type ScreeningScan = {
  score: number
  risk_label: string
  model_version: string
  metadata: Record<string, unknown>
  captured_at: string
  relative_time: string
}

export type ScreeningModalitySummary = {
  modality: string
  label: string
  scans: ScreeningScan[]
  latest: ScreeningScan
  trend: 'first' | 'worsening' | 'improving' | 'stable'
  delta_score: number | null
  sparkline: number[]
  scan_count: number
}

export async function getScreeningHistory(patientId?: string) {
  const query = patientId ? `?patient_id=${encodeURIComponent(patientId)}` : ''
  return getJson<{ modalities: ScreeningModalitySummary[]; total_scans: number }>(
    `/monitoring/screening-history${query}`,
  )
}

export type DiseaseProgressionAssessment = {
  id: number
  tier: 'low' | 'high' | 'critical'
  score: number
  confidence: number
  n_models_used: number
  assessed_at: string
  relative_time: string
}

export type DiseaseProgression = {
  assessments: DiseaseProgressionAssessment[]
  trend: 'first' | 'worsening' | 'stable' | 'improving'
  delta_score?: number
  recent_score_delta?: number | null
  delta_confidence?: number
  tier_journey?: string[]
  tier_escalations?: number
  n_assessments?: number
  period_days?: number
  modalities_evolution?: { first: number; last: number }
  confidence_evolution?: { first: number; last: number; delta: number }
  active_alerts_count?: number
}

export async function getDiseaseProgression(patientId?: string) {
  const query = patientId ? `?patient_id=${encodeURIComponent(patientId)}` : ''
  return getJson<DiseaseProgression>(`/monitoring/disease-progression${query}`)
}
